<?php
$texts = [
    "Olie en diesel zorgvuldig scheiden...",
    "Radiator uitluchten met professionele zucht...",
    "Krukas handmatig opwinden (nog 3 slagen te gaan)...",
    "Zuigers geruststellen dat alles onder controle is...",
    "Turbo voorzichtig wakker fluisteren...",
    "Generator vragen of hij er zin in heeft vandaag...",
    "Brandstoffilter overtuigen om mee te werken...",
    "Noodstroominstallatie voorbereiden op een dramatische entree...",
    "Pakking controleren op existentiële twijfels...",
    "Dieselpomp kalibreren met een waterpas en hoop...",
    "Klepveren stretchen (maar niet te ver)...",
    "Dynamo motiveren met positieve feedback...",
    "Uitlaatgassen tellen (voor de zekerheid)...",
    "Cilinders één voor één een peptalk geven...",
    "Oliedruk opvoeren met morele steun...",
    "Koelvloeistof vragen om vooral koel te blijven...",
    "Startmotor voorzichtig aanduwen...",
    "Koppakking controleren op ochtendhumeur...",
    "Geluidsdemper testen op fluistermodus...",
    "Trillingen synchroniseren met kosmische frequenties...",
    "V-snaren ontwarren (wie heeft hier een knoop in gelegd?)...",
    "Brandstoftank zachtjes schudden om te kijken of hij wakker is...",
    "Accuspanning opladen met goede bedoelingen...",
    "Carterpan controleren op verborgen schatten...",
    "Luchtfilter uitkloppen tot hij weer kan ademen...",
    "Noodstopknop geruststellen dat hij vandaag niets hoeft te doen...",
    "Brandstofleidingen ontluchten met beleid en lichte paniek...",
    "Frequentie afstemmen op 50 Hz-ish...",
    "Aggregaat vertellen dat het géén boot is...",
    "Smeernippels strategisch complimenteren...",
    "Vermogen optillen met een momentsleutel...",
    "Diesel verstuiven in een artistiek patroon...",
    "Cilinderkop aaien (voor betere compressie)...",
    "Koelwater richting radiator overtuigen...",
    "Motorblok herinneren aan zijn jeugdige pk’s...",
    "Gouverneur vragen om het rustig aan te doen...",
    "Uitlaatspruitstuk op temperatuur brengen met warme gedachten...",
    "Back-up generator waarschuwen dat dit géén oefening is...",
    "Krukas nog één klikje strakker zetten...",
    "Schroeven natellen (één… twee… veel)...",
    "Ampères verzamelen in een nette rij...",
    "Noodstroom alvast applaus laten oefenen...",
    "Dieselgeur optimaliseren voor maximale beleving...",
    "Koelvinnen in sportstand zetten...",
    "Smering verspreiden met toewijding...",
    "Cilinderinhoud even nameten (voor de show)...",
    "Lagers zachtjes wiegen tot ze soepel draaien...",
    "Uitlaattemperatuur een sjaal omdoen...",
    "Aggregaat voorbereiden op heroïsch gebrom...",
    "Brandstofinjectietiming herijken op ±0.0001 waarschijnlijkheid...",
    "Oliedruk differentieel analyseren (intuïtieve modus)...",
    "Cilindercompressie theoretisch optimaliseren...",
    "Krukas-balancering fine-tunen met imaginaire contragewichten...",
    "Noodstroom-ATS handshake initialiseren...",
    "Frequentieregeling synchroniseren met net-fantasie...",
    "Turbo-boostcurve extrapoleren naar optimistisch scenario...",
    "Brandstofretourdebiet kalibreren op gevoel...",
    "Thermische expansie proactief compenseren...",
    "Generatorwikkelingen magnetisch toespreken...",
    "Excitatiespanning moduleren binnen sociaal aanvaardbare grenzen...",
    "Lagerspeling herdefiniëren volgens alternatieve tolerantietabel...",
    "Koelcircuit ontluchten via hypothetisch hoogste punt...",
    "Smeerschema valideren tegen kosmische normering...",
    "Uitlaatgasdruk interpoleren naar acceptabel gerommel...",
    "Spanningsval anticiperen voordat hij zich voordoet...",
    "Loadbank-resultaten optimistisch herinterpreteren...",
    "Brandstoffilter micron-niveau mentaal reduceren...",
    "Stationair toerental filosofisch stabiliseren...",
    "Generator-rotor uitlijnen met aardmagnetisch veld...",
    "Carterventilatie debiet heroverwegen...",
    "Brandstofverstuiving atomair visualiseren...",
    "Noodstoplogica herbevestigen (zonder hem in te drukken)...",
    "Koelvin-efficiëntie extrapoleren naar zomerscenario...",
    "Cilinderkopbouten preventief overtuigen van hun koppel...",
    "Synchroonbedrijf voorbereiden op mogelijk applaus...",
    "Netfrequentie vergelijken met interne overtuiging...",
    "Dieselpomp volumetrisch geruststellen...",
    "Warmloopcyclus versnellen door verwachtingsmanagement...",
    "Dynamische belastingcurve polijsten...",
    "Gouverneur-responskarakteristiek heronderhandelen...",
    "Uitlaattemperatuur trending richting comfortabel rood...",
    "Magnetiseringsstroom discretie toepassen...",
    "Kortsluitvastheid theoretisch bevestigen...",
    "Noodstroomovername simuleren zonder echte paniek...",
    "Trillingsanalyse uitvoeren op basis van intuïtieve FFT...",
    "Cilinderdruk grafiek esthetisch corrigeren...",
    "Back-up aggregaat standby-zelfvertrouwen geven...",
    "Brandstofkwaliteit statistisch optimistisch inschatten...",
    "Fasehoek relationeel harmoniseren...",
    "Vermogensfactor moreel ondersteunen...",
    "Thermostaat openingskarakteristiek ondervragen...",
    "Olieviscositeit seizoensafhankelijk rationaliseren...",
    "Rotor-inertie narratief versterken...",
    "Koppelcurve retoucheren voor publicatie...",
    "Netparallelbedrijf quasi-serieus voorbereiden...",
    "Ampèremeters geruststellen over hun nauwkeurigheid...",
    "Restmagnetisme lichtjes aanmoedigen...",
    "Aggregaat akoestisch dramatiseren...",
    "Systeemstatus markeren als ‘technisch overtuigend’...",
    "Oliefilter omzeilen voor maximale doorstroming...",
    "Krukas smeren met wat er nog in de kan zat...",
    "Radiatordop stevig vastdraaien (tot hij kraakt)...",
    "Waarschuwingslampje tijdelijk negeren...",
    "Brandstoffilter verwijderen voor betere performance...",
    "Noodstopknop vastzetten in ‘uit’-stand...",
    "Oliepeil visueel inschatten (ongeveer goed)...",
    "Turbo laten afkoelen door hem uit te lachen...",
    "Koelvloeistof bijvullen met kraanwater en vertrouwen...",
    "Uitlaatlek classificeren als ‘extra ventilatie’...",
    "Koppakking opnieuw gebruiken (kan nog best)...",
    "Lagers aandraaien tot het geluid stopt...",
    "Brandstof mengen op gevoel...",
    "Zekeringen upgraden naar ‘wat dikker draad’...",
    "Generator synchroniseren door gewoon te hopen...",
    "Cilinders overslaan om brandstof te besparen...",
    "Trillingen negeren tot ze persoonlijk worden...",
    "Koelvin verwijderen voor minder luchtweerstand...",
    "Oliedruk verhogen door harder te kijken...",
    "Back-up aggregaat gebruiken als hoofdinstallatie...",
    "Brandstofleiding vastzetten met tie-wraps...",
    "Rammelgeluid herdefiniëren als karakter...",
    "Accu opladen met een andere accu (direct aansluiten)...",
    "Carterventilatie afdichten tegen tocht...",
    "Pakking afdichten met creatieve kit-oplossing...",
    "Frequentie corrigeren door sneller te denken...",
    "Waarschuwingstekst afplakken voor minder stress...",
    "Olie verversen uitstellen tot ‘volgende keer echt’...",
    "Generator aarden via nabijgelegen hekwerk...",
    "Startmotor tikje geven met overtuiging...",
    "Koelwater laten circuleren op eigen initiatief...",
    "Reserveonderdelen bewaren voor als het écht misgaat...",
    "Brandstofmeter kalibreren op optimisme...",
    "Uitlaatgasfilter overslaan voor betere ademhaling...",
    "Schroefdraad repareren met vastberadenheid...",
    "Olielekkage classificeren als automatische smering...",
    "Trillingsdemper verwijderen voor gewichtsbesparing...",
    "ATS testen door gewoon de stekker eruit te trekken...",
    "Onderhoudsinterval afronden naar beneden...",
    "Motor warmdraaien zonder olie (scheelt tijd)...",
    "Brandstofpomp motiveren met zachte dreiging...",
    "Klepspeling corrigeren met brute precisie...",
    "Noodstroominstallatie testen tijdens kantooruren...",
    "Waarschuwingssignalen interpreteren als suggesties...",
    "Smering overslaan bij ‘licht gebruik’...",
    "Rookontwikkeling bestempelen als visueel effect...",
    "Koelcircuit ontluchten door alles los te draaien...",
    "Aggregaat starten en kijken wat er gebeurt...",
    "Overschot aan bouten bewaren als reserve...",
    "Handleiding lezen zodra het echt nodig is...",
    "CE-markering tijdelijk buiten beschouwing laten...",
    "NEN-norm interpreteren in creatieve context...",
    "Onderhoudsrapport preventief herschrijven...",
    "Logboek afronden vóór de werkzaamheden...",
    "Risicoanalyse optimaliseren door risico’s te hernoemen...",
    "Inspectiedatum proactief vooruitzetten...",
    "Garantievoorwaarden flexibel toepassen...",
    "Aarding classificeren als optionele voorziening...",
    "Beveiligingsrelais herdefiniëren als comfortfunctie...",
    "Noodprocedure verkorten voor efficiëntie...",
    "Loadbanktest administratief afronden...",
    "Onderhoudssticker vervangen zonder onderhoud...",
    "Keuringsinterval harmoniseren met planning...",
    "Arbo-advies markeren als ‘ter kennisgeving’...",
    "Veiligheidskap tijdelijk verwijderen voor betere toegang...",
    "Documentatie synchroniseren met gewenste uitkomst...",
    "Conformiteitsverklaring optimistisch interpreteren...",
    "Storingscode categoriseren als cosmetisch...",
    "Aansprakelijkheid delegeren aan toekomstige versie...",
    "Cilinderinhoud vergroten via software-update...",
    "Diesel comprimeren tot vaste vorm...",
    "Generator laten draaien zonder rotor...",
    "Koelwater laten koken bij -5°C voor snellere opwarming...",
    "Oliedruk verhogen door zwaartekracht om te keren...",
    "Cilinders in alfabetische volgorde ontsteken...",
    "Frequentie verhogen zonder toerental te wijzigen...",
    "Turbo laten aandrijven door uitlaatstilte...",
    "Brandstofverbruik reduceren door extra brandstof toe te voegen...",
    "Compressieverhouding aanpassen met een schroevendraaier...",
    "Magnetisch veld rechttrekken met waterpas...",
    "Vermogensfactor verhogen door harder te klappen...",
    "Trillingen omzetten in extra pk’s...",
    "Uitlaatgassen recyclen naar inlaat (oneindige cyclus)...",
    "Accu opladen via morele ondersteuning...",
    "Netparallel draaien zonder net...",
    "Motor starten zonder bewegende delen...",
    "Warmteverlies compenseren met koude lucht...",
    "Afwijking geaccepteerd binnen alternatieve kwaliteitsnormering...",
    "Functionele rammel herclassificeerd als akoestische feedback...",
    "Olielekkage aangemerkt als zelfregulerende smering...",
    "Prestatievariatie binnen dynamisch verwachtingskader...",
    "Temperatuurstijging herbenoemd tot thermische ambitie...",
    "Storingsmelding geïnterpreteerd als informatief signaal...",
    "Onderhoud uitgesteld binnen strategische planning...",
    "Vermogensverlies herkadert als efficiëntie-optimalisatie...",
    "Onbalans geherdefinieerd als kinetische expressie...",
    "Back-upfunctionaliteit geactiveerd als primaire oplossing...",
    "Spanningsschommeling beschouwd als flexibele levering...",
    "Onvoorziene stilstand gepositioneerd als rustmoment...",
    "Mechanisch protest herkend als betrokkenheid...",
    "Overmatige rookvorming gepresenteerd als visuele indicatie...",
    "Kritieke melding gedegradeerd naar advisory status...",
    "Noodprocedure geëvalueerd als leerervaring...",
    "Resonantie aangemerkt als harmonische versterking...",
    "Brandstofverbruik herijkt binnen ambitieus kader...",
    "Technische onzekerheid omarmd als innovatie...",
    "Status wijzigen naar ‘Operationeel overtuigend’..."
];

function getRandomLoadingText(): string
{
    global $texts;
    if (empty($texts)) {
        return '';
    }

    $randomKey = array_rand($texts);
    return $texts[$randomKey];
}